# Site setings
name: 'UX in Practice'
description: 'User Experience and Design'
# Sidebar about text
site_description: 'Articles and content around User Experience (UX), Design, and Product stuff'
logo:
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: http://www.uxinpractice.com/
disqus:
mailchimp_url:
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: youremail@email.com
contact_page_description: "Contact Us"
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'username'
facebook: 
github: 'username'
codepen: 'username'
dribbble: 'username'
medium: 'ux-in-practice'
instagram: 'username'
pinterest:
linkedin: 'username'

# Navigation
navigation:
  - text: About
    url: /about.html
  - text: Style Guide
    url: /style-guide.html
  - text: Contact Me
    url: /contact.html

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-author-page

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
# permalink: /:title
permalink: pretty

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

theme: jekyll-theme-cayman